# Import Libraries

In [112]:
import pandas as pd
import numpy as np
import re
import string
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer

# Download NLTK Resources (Run Once)

nltk.download("punkt")
nltk.download("stopwords")
nltk.download("wordnet")

# Create Sample Dataset or working a Dataset

In [113]:
data = {
    "text": [
        "I LOVE Machine Learning!!! Visit https://google.com 😊",
        "<p>This is an HTML tag.</p>",
        "Email me at abc123@gmail.com",
        "@john Python is AMAZING!!! #Python #AI",
        "The price is 9999 dollars.",
        "I am learning NLP with ChatGPT.",
        "This movie was not good at all.",
        "This movie was fantastic and amazing.",
        np.nan,
        "Python Python Python is easy easy easy."
    ],
    "label": [
        1,
        0,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1
    ]
}

df = pd.DataFrame(data)

In [114]:
df

                                                text  label
0  I LOVE Machine Learning!!! Visit https://googl...      1
1                        <p>This is an HTML tag.</p>      0
2                       Email me at abc123@gmail.com      0
3             @john Python is AMAZING!!! #Python #AI      1
4                         The price is 9999 dollars.      0
5                    I am learning NLP with ChatGPT.      1
6                    This movie was not good at all.      0
7              This movie was fantastic and amazing.      1
8                                                NaN      0
9            Python Python Python is easy easy easy.      1

# Save Dataframe

In [115]:
df = df.to_csv('NLP_Dataset.csv')

# Remove Duplicate Rows

In [116]:
df = pd.read_csv('NLP_Dataset.csv')

In [117]:
df.drop_duplicates(inplace=True)

# Handle Missing Values

In [118]:
df["text"] = df["text"].fillna("")

In [119]:
df

   Unnamed: 0                                               text  label
0           0  I LOVE Machine Learning!!! Visit https://googl...      1
1           1                        <p>This is an HTML tag.</p>      0
2           2                       Email me at abc123@gmail.com      0
3           3             @john Python is AMAZING!!! #Python #AI      1
4           4                         The price is 9999 dollars.      0
5           5                    I am learning NLP with ChatGPT.      1
6           6                    This movie was not good at all.      0
7           7              This movie was fantastic and amazing.      1
8           8                                                         0
9           9            Python Python Python is easy easy easy.      1

# Convert to Lowercase

In [120]:
df["text"] = df["text"].str.lower()

In [121]:
df.head()

   Unnamed: 0                                               text  label
0           0  i love machine learning!!! visit https://googl...      1
1           1                        <p>this is an html tag.</p>      0
2           2                       email me at abc123@gmail.com      0
3           3             @john python is amazing!!! #python #ai      1
4           4                         the price is 9999 dollars.      0

# Remove HTML Tags

In [122]:
def remove_html(text):
    return re.sub(r'<.*?>', '', text)

df["text"] = df["text"].apply(remove_html)

In [123]:
df

   Unnamed: 0                                               text  label
0           0  i love machine learning!!! visit https://googl...      1
1           1                               this is an html tag.      0
2           2                       email me at abc123@gmail.com      0
3           3             @john python is amazing!!! #python #ai      1
4           4                         the price is 9999 dollars.      0
5           5                    i am learning nlp with chatgpt.      1
6           6                    this movie was not good at all.      0
7           7              this movie was fantastic and amazing.      1
8           8                                                         0
9           9            python python python is easy easy easy.      1

# Remove URLs

In [124]:
def remove_url(text):
    return re.sub(r'https?://\S+|www\.\S+', '', text)

df["text"] = df["text"].apply(remove_url)

In [125]:
df

   Unnamed: 0                                     text  label
0           0      i love machine learning!!! visit  😊      1
1           1                     this is an html tag.      0
2           2             email me at abc123@gmail.com      0
3           3   @john python is amazing!!! #python #ai      1
4           4               the price is 9999 dollars.      0
5           5          i am learning nlp with chatgpt.      1
6           6          this movie was not good at all.      0
7           7    this movie was fantastic and amazing.      1
8           8                                               0
9           9  python python python is easy easy easy.      1

# Remove Email Addresses

In [126]:
def remove_email(text):
    return re.sub(r'\S+@\S+', '', text)

df["text"] = df["text"].apply(remove_email)

In [127]:
df

   Unnamed: 0                                     text  label
0           0      i love machine learning!!! visit  😊      1
1           1                     this is an html tag.      0
2           2                             email me at       0
3           3   @john python is amazing!!! #python #ai      1
4           4               the price is 9999 dollars.      0
5           5          i am learning nlp with chatgpt.      1
6           6          this movie was not good at all.      0
7           7    this movie was fantastic and amazing.      1
8           8                                               0
9           9  python python python is easy easy easy.      1

# Remove @Mentions

In [128]:
def remove_mentions(text):
    return re.sub(r'@\w+', '', text)

df["text"] = df["text"].apply(remove_mentions)

In [129]:
df

   Unnamed: 0                                     text  label
0           0      i love machine learning!!! visit  😊      1
1           1                     this is an html tag.      0
2           2                             email me at       0
3           3         python is amazing!!! #python #ai      1
4           4               the price is 9999 dollars.      0
5           5          i am learning nlp with chatgpt.      1
6           6          this movie was not good at all.      0
7           7    this movie was fantastic and amazing.      1
8           8                                               0
9           9  python python python is easy easy easy.      1

# Remove Emojis

In [130]:
def remove_emoji(text):
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"
        "\U0001F300-\U0001F5FF"
        "\U0001F680-\U0001F6FF"
        "\U0001F1E0-\U0001F1FF"
        "]+",
        flags=re.UNICODE
    )

    return emoji_pattern.sub('', text)

df["text"] = df["text"].apply(remove_emoji)

# Remove Punctuation

In [131]:
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))

df["text"] = df["text"].apply(remove_punctuation)

In [132]:
df

   Unnamed: 0                                    text  label
0           0         i love machine learning visit        1
1           1                     this is an html tag      0
2           2                            email me at       0
3           3             python is amazing python ai      1
4           4               the price is 9999 dollars      0
5           5          i am learning nlp with chatgpt      1
6           6          this movie was not good at all      0
7           7    this movie was fantastic and amazing      1
8           8                                              0
9           9  python python python is easy easy easy      1

# Remove Numbers

In [133]:
def remove_numbers(text):
    return re.sub(r'\d+', '', text)

df["text"] = df["text"].apply(remove_numbers)

In [134]:
df

   Unnamed: 0                                    text  label
0           0         i love machine learning visit        1
1           1                     this is an html tag      0
2           2                            email me at       0
3           3             python is amazing python ai      1
4           4                   the price is  dollars      0
5           5          i am learning nlp with chatgpt      1
6           6          this movie was not good at all      0
7           7    this movie was fantastic and amazing      1
8           8                                              0
9           9  python python python is easy easy easy      1

# Remove Extra Spaces

In [135]:
def remove_spaces(text):
    return " ".join(text.split())

df["text"] = df["text"].apply(remove_spaces)

In [136]:
df

   Unnamed: 0                                    text  label
0           0           i love machine learning visit      1
1           1                     this is an html tag      0
2           2                             email me at      0
3           3             python is amazing python ai      1
4           4                    the price is dollars      0
5           5          i am learning nlp with chatgpt      1
6           6          this movie was not good at all      0
7           7    this movie was fantastic and amazing      1
8           8                                              0
9           9  python python python is easy easy easy      1

# Tokenization

In [137]:
df["tokens"] = df["text"].apply(word_tokenize)

In [138]:
df

,Unnamed: 0,text,label,tokens
0,0,i love machine learning visit,1,"[i, love, machine, learning, visit]"
1,1,this is an html tag,0,"[this, is, an, html, tag]"
2,2,email me at,0,"[email, me, at]"
3,3,python is amazing python ai,1,"[python, is, amazing, python, ai]"
4,4,the price is dollars,0,"[the, price, is, dollars]"
5,5,i am learning nlp with chatgpt,1,"[i, am, learning, nlp, with, chatgpt]"
6,6,this movie was not good at all,0,"[this, movie, was, not, good, at, all]"
7,7,this movie was fantastic and amazing,1,"[this, movie, was, fantastic, and, amazing]"
8,8,,0,[]
9,9,python python python is easy easy easy,1,"[python, python, python, is, easy, easy, easy]"

In [139]:
df.tokens

0               [i, love, machine, learning, visit]
1                         [this, is, an, html, tag]
2                                   [email, me, at]
3                 [python, is, amazing, python, ai]
4                         [the, price, is, dollars]
5             [i, am, learning, nlp, with, chatgpt]
6            [this, movie, was, not, good, at, all]
7       [this, movie, was, fantastic, and, amazing]
8                                                []
9    [python, python, python, is, easy, easy, easy]
Name: tokens, dtype: object

# Remove Stopwords

In [140]:
stop_words = set(stopwords.words("english"))

In [141]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [142]:
def remove_stopwords(words):
    return [word for word in words if word not in stop_words]

df["tokens"] = df["tokens"].apply(remove_stopwords)

In [143]:
df

,Unnamed: 0,text,label,tokens
0,0,i love machine learning visit,1,"[love, machine, learning, visit]"
1,1,this is an html tag,0,"[html, tag]"
2,2,email me at,0,[email]
3,3,python is amazing python ai,1,"[python, amazing, python, ai]"
4,4,the price is dollars,0,"[price, dollars]"
5,5,i am learning nlp with chatgpt,1,"[learning, nlp, chatgpt]"
6,6,this movie was not good at all,0,"[movie, good]"
7,7,this movie was fantastic and amazing,1,"[movie, fantastic, amazing]"
8,8,,0,[]
9,9,python python python is easy easy easy,1,"[python, python, python, easy, easy, easy]"

# Stemming

In [144]:
stemmer = PorterStemmer()

def stem_words(words):
    return [stemmer.stem(word) for word in words]

df["stemmed"] = df["tokens"].apply(stem_words)

In [145]:
df

,Unnamed: 0,text,label,tokens,stemmed
0,0,i love machine learning visit,1,"[love, machine, learning, visit]","[love, machin, learn, visit]"
1,1,this is an html tag,0,"[html, tag]","[html, tag]"
2,2,email me at,0,[email],[email]
3,3,python is amazing python ai,1,"[python, amazing, python, ai]","[python, amaz, python, ai]"
4,4,the price is dollars,0,"[price, dollars]","[price, dollar]"
5,5,i am learning nlp with chatgpt,1,"[learning, nlp, chatgpt]","[learn, nlp, chatgpt]"
6,6,this movie was not good at all,0,"[movie, good]","[movi, good]"
7,7,this movie was fantastic and amazing,1,"[movie, fantastic, amazing]","[movi, fantast, amaz]"
8,8,,0,[],[]
9,9,python python python is easy easy easy,1,"[python, python, python, easy, easy, easy]","[python, python, python, easi, easi, easi]"

# Lemmatization

In [146]:
lemmatizer = WordNetLemmatizer()

def lemma_words(words):
    return [lemmatizer.lemmatize(word) for word in words]

df["lemmatized"] = df["tokens"].apply(lemma_words)

In [147]:
df

,Unnamed: 0,text,label,tokens,stemmed,lemmatized
0,0,i love machine learning visit,1,"[love, machine, learning, visit]","[love, machin, learn, visit]","[love, machine, learning, visit]"
1,1,this is an html tag,0,"[html, tag]","[html, tag]","[html, tag]"
2,2,email me at,0,[email],[email],[email]
3,3,python is amazing python ai,1,"[python, amazing, python, ai]","[python, amaz, python, ai]","[python, amazing, python, ai]"
4,4,the price is dollars,0,"[price, dollars]","[price, dollar]","[price, dollar]"
5,5,i am learning nlp with chatgpt,1,"[learning, nlp, chatgpt]","[learn, nlp, chatgpt]","[learning, nlp, chatgpt]"
6,6,this movie was not good at all,0,"[movie, good]","[movi, good]","[movie, good]"
7,7,this movie was fantastic and amazing,1,"[movie, fantastic, amazing]","[movi, fantast, amaz]","[movie, fantastic, amazing]"
8,8,,0,[],[],[]
9,9,python python python is easy easy easy,1,"[python, python, python, easy, easy, easy]","[python, python, python, easi, easi, easi]","[python, python, python, easy, easy, easy]"

# Join Words Back

In [148]:
df["clean_text"] = df["lemmatized"].apply(lambda x: " ".join(x))

In [149]:
df

,Unnamed: 0,text,label,tokens,stemmed,lemmatized,clean_text
0,0,i love machine learning visit,1,"[love, machine, learning, visit]","[love, machin, learn, visit]","[love, machine, learning, visit]",love machine learning visit
1,1,this is an html tag,0,"[html, tag]","[html, tag]","[html, tag]",html tag
2,2,email me at,0,[email],[email],[email],email
3,3,python is amazing python ai,1,"[python, amazing, python, ai]","[python, amaz, python, ai]","[python, amazing, python, ai]",python amazing python ai
4,4,the price is dollars,0,"[price, dollars]","[price, dollar]","[price, dollar]",price dollar
5,5,i am learning nlp with chatgpt,1,"[learning, nlp, chatgpt]","[learn, nlp, chatgpt]","[learning, nlp, chatgpt]",learning nlp chatgpt
6,6,this movie was not good at all,0,"[movie, good]","[movi, good]","[movie, good]",movie good
7,7,this movie was fantastic and amazing,1,"[movie, fantastic, amazing]","[movi, fantast, amaz]","[movie, fantastic, amazing]",movie fantastic amazing
8,8,,0,[],[],[],
9,9,python python python is easy easy easy,1,"[python, python, python, easy, easy, easy]","[python, python, python, easi, easi, easi]","[python, python, python, easy, easy, easy]",python python python easy easy easy

# Remove Frequent Words (Top 5)

In [150]:
from collections import Counter

all_words = " ".join(df["clean_text"]).split()

counter = Counter(all_words)

frequent_words = [word for word, count in counter.most_common(5)]

print(frequent_words)

def remove_frequent(text):
    return " ".join(
        word for word in text.split()
        if word not in frequent_words
    )

df["clean_text"] = df["clean_text"].apply(remove_frequent)

['python', 'easy', 'learning', 'amazing', 'movie']

In [151]:
df

,Unnamed: 0,text,label,tokens,stemmed,lemmatized,clean_text
0,0,i love machine learning visit,1,"[love, machine, learning, visit]","[love, machin, learn, visit]","[love, machine, learning, visit]",love machine visit
1,1,this is an html tag,0,"[html, tag]","[html, tag]","[html, tag]",html tag
2,2,email me at,0,[email],[email],[email],email
3,3,python is amazing python ai,1,"[python, amazing, python, ai]","[python, amaz, python, ai]","[python, amazing, python, ai]",ai
4,4,the price is dollars,0,"[price, dollars]","[price, dollar]","[price, dollar]",price dollar
5,5,i am learning nlp with chatgpt,1,"[learning, nlp, chatgpt]","[learn, nlp, chatgpt]","[learning, nlp, chatgpt]",nlp chatgpt
6,6,this movie was not good at all,0,"[movie, good]","[movi, good]","[movie, good]",good
7,7,this movie was fantastic and amazing,1,"[movie, fantastic, amazing]","[movi, fantast, amaz]","[movie, fantastic, amazing]",fantastic
8,8,,0,[],[],[],
9,9,python python python is easy easy easy,1,"[python, python, python, easy, easy, easy]","[python, python, python, easi, easi, easi]","[python, python, python, easy, easy, easy]",

# Remove Rare Words

In [152]:
# split then count each word
word_counts = Counter(all_words)

In [153]:
word_counts

Counter({'python': 5,
         'easy': 3,
         'learning': 2,
         'amazing': 2,
         'movie': 2,
         'love': 1,
         'machine': 1,
         'visit': 1,
         'html': 1,
         'tag': 1,
         'email': 1,
         'ai': 1,
         'price': 1,
         'dollar': 1,
         'nlp': 1,
         'chatgpt': 1,
         'good': 1,
         'fantastic': 1})

In [154]:
# Find Rare word
rare_words = [
    word
    for word, count in word_counts.items()
    if count == 1
]
rare_words

['love',
 'machine',
 'visit',
 'html',
 'tag',
 'email',
 'ai',
 'price',
 'dollar',
 'nlp',
 'chatgpt',
 'good',
 'fantastic']

In [155]:
# Remove Rare Words
def remove_rare_words(text):
    return " ".join(
        word
        for word in text.split()
        if word not in rare_words
    )

df["clean_text"] = df["text"].apply(remove_rare_words)

In [156]:
df

,Unnamed: 0,text,label,tokens,stemmed,lemmatized,clean_text
0,0,i love machine learning visit,1,"[love, machine, learning, visit]","[love, machin, learn, visit]","[love, machine, learning, visit]",i learning
1,1,this is an html tag,0,"[html, tag]","[html, tag]","[html, tag]",this is an
2,2,email me at,0,[email],[email],[email],me at
3,3,python is amazing python ai,1,"[python, amazing, python, ai]","[python, amaz, python, ai]","[python, amazing, python, ai]",python is amazing python
4,4,the price is dollars,0,"[price, dollars]","[price, dollar]","[price, dollar]",the is dollars
5,5,i am learning nlp with chatgpt,1,"[learning, nlp, chatgpt]","[learn, nlp, chatgpt]","[learning, nlp, chatgpt]",i am learning with
6,6,this movie was not good at all,0,"[movie, good]","[movi, good]","[movie, good]",this movie was not at all
7,7,this movie was fantastic and amazing,1,"[movie, fantastic, amazing]","[movi, fantast, amaz]","[movie, fantastic, amazing]",this movie was and amazing
8,8,,0,[],[],[],
9,9,python python python is easy easy easy,1,"[python, python, python, easy, easy, easy]","[python, python, python, easi, easi, easi]","[python, python, python, easy, easy, easy]",python python python is easy easy easy

# Convert Text into TF-IDF Features

In [157]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(df["clean_text"])

y = df["label"]

In [158]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 29 stored elements and shape (10, 18)>

In [159]:
y

0    1
1    0
2    0
3    1
4    0
5    1
6    0
7    1
8    0
9    1
Name: label, dtype: int64

# Train-Test Split

In [160]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [161]:
print(df["label"].value_counts())

label
1    5
0    5
Name: count, dtype: int64

In [162]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8, 18)
(2, 18)
(8,)
(2,)

In [163]:
print(df["clean_text"].head())

0                  i learning
1                  this is an
2                       me at
3    python is amazing python
4              the is dollars
Name: clean_text, dtype: object

In [164]:
print(X.shape)

(10, 18)

In [165]:
print(df["label"].value_counts())

label
1    5
0    5
Name: count, dtype: int64

In [166]:
y_pred = model.predict(X_test)

In [167]:
y_pred

array([1, 1])